#!/bin/bash
#
# FileName: version
# Description: Updates or prints current version number crom cmake config.
# 
# Copyright (C) 2014  K M Masum Habib <masum.habib@gmail.com>
#
# Created: 18 June 2014.

function usage(){
    echo "Usage: version [x.yy.z]"
    echo "  When no option is given, it return version string."
    echo "  options: " 
    echo "    x.yy.z - new version numbers."
    exit 0
}

other_files="tests/test_dirac_band.py tests/test_dirac_transport.py"

major_keyword="set(QMICAD_MAJOR"
minor_keyword="set(QMICAD_MINOR"
patch_keyword="set(QMICAD_PATCH"
cmake_file="CMakeLists.txt"

version_major=`grep "$major_keyword [0-9])" $cmake_file | sed 's/[^0-9]//g'`
version_minor=`grep "$minor_keyword [0-9][0-9])" $cmake_file | sed 's/[^0-9]//g'`
version_patch=`grep "$patch_keyword [0-9])" $cmake_file | sed 's/[^0-9]//g'`

new_patch=$version_patch
new_minor=$version_minor
new_major=$version_major

if [[ $# -eq 0 ]]; then
    echo "v$version_major.$version_minor.$version_patch" 
elif [[ $# -eq 1 ]]; then
    IFS='.' read -ra vers <<< "$1"
    nvers=${#vers[@]}
    if [[ $nvers -eq 1 ]];then
        new_patch=${vers[0]}
    elif [[ $nvers -eq 2 ]];then
        new_patch=${vers[1]}
        new_minor=${vers[0]}
    elif [[ $nvers -eq 3 ]];then
        new_patch=${vers[2]}
        new_minor=${vers[1]}
        new_major=${vers[0]}
    else
        usage
    fi

    # Update CMakeLists.txt
    echo -n "Updateing $cmake_file ... "
    cp $cmake_file $cmake_file.IN
    sed -e "s/$patch_keyword $version_patch)/$patch_keyword $new_patch)/g" -e "s/$minor_keyword $version_minor)/$minor_keyword $new_minor)/g" -e "s/$major_keyword $version_major)/$major_keyword $new_major)/g" < $cmake_file.IN > $cmake_file
    rm $cmake_file.IN
    echo "done."

    # update test scripts
    for file in $other_files; do
        echo -n "Updateing $file ... "
        cp $file $file.IN
        sed -e "s/$version_major.$version_minor.$version_patch/$new_major.$new_minor.$new_patch/g" < $file.IN > $file
        rm $file.IN
        echo "done."
    done

    echo "Updated to v$new_major.$new_minor.$new_patch" 
else
    uasge
fi
