#ifndef CONFIG_H
    #define CONFIG_H

    #define QUEST_VERSION_MAJOR "@QUEST_MAJOR@"
    #define QUEST_VERSION_MINOR "@QUEST_MINOR@"
    #define QUEST_VERSION_PATCH "@QUEST_PATCH@"
    #define QUEST_VERSION_BUILD "@QUEST_BUILD@"

#endif
