#set(MACHINE_NAME rivanna)
#list(APPEND CMAKE_PREFIX_PATH /share/apps/python/2.7.6)
#list(APPEND CMAKE_PREFIX_PATH /share/apps/hdf5/openmpi/gcc/1.8.13)
#list(APPEND CMAKE_PREFIX_PATH /share/apps/boost.MPI/openmpi/gcc/1.55.0)
#list(APPEND CMAKE_PREFIX_PATH $ENV{HOME}/usr)
#set(CMAKE_PREFIX_PATH $ENV{HOME}/usr)
#set(Boost_INCLUDE_DIR $ENV{HOME}/usr/include)
#set(Boost_LIBRARY_DIR $ENV{HOME}/usr/lib)
