#ifndef CONFIG_H
    #define CONFIG_H

    #define QMICAD_VERSION_MAJOR "@QMICAD_MAJOR@"
    #define QMICAD_VERSION_MINOR "@QMICAD_MINOR@"
    #define QMICAD_VERSION_PATCH "@QMICAD_PATCH@"

    #define QMICAD_VERSION "@QMICAD_VERSION@"

#endif
